// <auto-generated />
namespace MazeGame.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class _280620170141 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_280620170141));
        
        string IMigrationMetadata.Id
        {
            get { return "201706272241159_280620170141"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
