// <auto-generated />
namespace MazeGame.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class _190617_0026 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_190617_0026));
        
        string IMigrationMetadata.Id
        {
            get { return "201706182126335_190617_0026"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
