// <auto-generated />
namespace MazeGame.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class _190617_003400 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_190617_003400));
        
        string IMigrationMetadata.Id
        {
            get { return "201706182134476_190617_003400"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
